// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PFM_project.Database.Repositories;

#nullable disable

namespace PFMproject.Migrations
{
    [DbContext(typeof(TranasactionsDBContext))]
    [Migration("20220725162655_Migrations100")]
    partial class Migrations100
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PFM_project.Database.Entities.CategoryEntity", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("parent_code")
                        .HasColumnType("text");

                    b.HasKey("code");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("PFM_project.Database.Entities.TransactionCategoryMapping", b =>
                {
                    b.Property<DateTime>("vreme")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CategoryId")
                        .HasColumnType("text");

                    b.Property<string>("TransactionID")
                        .HasColumnType("text");

                    b.Property<double>("amount")
                        .HasColumnType("double precision");

                    b.HasKey("vreme");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TransactionID");

                    b.ToTable("junction", (string)null);
                });

            modelBuilder.Entity("PFM_project.Database.Entities.TransactionsEntity", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("Directions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("amount")
                        .HasColumnType("double precision");

                    b.Property<string>("beneficiaryname")
                        .HasColumnType("text");

                    b.Property<string>("catcode")
                        .HasColumnType("text");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int>("mcc")
                        .HasColumnType("integer");

                    b.Property<string>("splits")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("catcode");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("PFM_project.Database.Entities.TransactionCategoryMapping", b =>
                {
                    b.HasOne("PFM_project.Database.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("PFM_project.Database.Entities.TransactionsEntity", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionID");

                    b.Navigation("Category");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("PFM_project.Database.Entities.TransactionsEntity", b =>
                {
                    b.HasOne("PFM_project.Database.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("catcode");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
